### ISSUE TITLE
`antarctic` colorscheme link is broken

### ISSUE THREAD

**Issue by spenserblack** [romainl/vim-rnb#19]
Looks like the link in the README points to a non-existent repository.

**Comment by romainl** [comment]
Yep, it looks like the author discreetly migrated his repositories to SourceHut.

Thank you!

**Comment by axvr** [comment]
It seems that the link to “Paper.vim” (by the same author) is broken too and is now located here: <https://git.sr.ht/~swalladge/paper.vim>

**Comment by romainl** [comment]
Thanks for spotting this.

**Comment by samuelallan72** [comment]
Sorry!  I forgot these were listed here.

**Comment by romainl** [comment]
@swalladge not the end of the world!

(and sr.ht++) ;-)
