### ISSUE TITLE
Files structure - makefile broken

### ISSUE THREAD

**Issue by samuelallan72** [romainl/vim-rnb#2]
The makefile was originally written to work with the template files in the colors/ directory, but the files have been moved to a src/ directory now. Maybe the colorscheme template files should stay in the colors/ directory for ease of use? Other files like a readme template could stay in src/

**Comment by romainl** [comment]
I'm trying to figure out a proper structure and a proper feature set as well (readme or not readme?) so I'll probably keep moving things around for a while… and breaking stuff in the process.

I don't expect this repo to be completely functional before this week-end.

**Comment by romainl** [comment]
The `Makefile` is working again.
