### ISSUE TITLE
Is setting `set t_Co=16` safe?

### ISSUE THREAD

**Issue by lifepillar** [romainl/vim-rnb#3]
You do this:

```vim
elseif &t_Co == 8 || $TERM !~# '^linux' || &t_Co == 16
    set t_Co=16
```

Is it safe to set `t_Co=16` when the terminal has only eight colors? Wouldn't it be better to use color names instead? If not, could you explain why? I am trying to decide which choice of color specifications is better for maximum portability.

**Comment by romainl** [comment]
> Is it safe to set t_Co=16 when the terminal has only eight colors?

I think it is.

> Wouldn't it be better to use color names instead?

In RNB I recommend going with color names. My reasoning is essentially that it is impossible to be certain that a given color has a given index and vice-versa across terminal emulators. The Windows console, for example, used to have a bunch of misplaced colors (blues and reds IIRC) so using a number to get a specific color, say "2" to get a "dark blue", wouldn't work as expected.

>  If not, could you explain why?

To be honest I think I `set t_Co=16` back when I used indexes for `cterm*` and I needed to ensure all my colors were usable for background, too. Now that I use names Vim should do the right thing automatically.

**Comment by romainl** [comment]
So I played with `t_Co` and it seems that setting it to `16` is still needed if I want to use colors 8-15 for background, whether I use numbers or names.

`$ TERM=xterm vim +vs` with `set t_Co=16` in `apprentice.vim`:

<img width="1075" alt="Capture d’écran 2019-05-30 à 10 37 12" src="https://user-images.githubusercontent.com/344335/58620273-f78f2600-82c6-11e9-8800-2d34365916d6.png">

`$ TERM=xterm vim +vs` with `set t_Co=16` commented out in `apprentice.vim`:

<img width="1075" alt="Capture d’écran 2019-05-30 à 10 37 27" src="https://user-images.githubusercontent.com/344335/58620276-fa8a1680-82c6-11e9-9c06-3f473641f59e.png">

The grey I use is "DarkGrey"/`8`.

**Comment by lifepillar** [comment]
Is that Terminal.app? I guess you also need to have *Use bright colours for bold text* in the Prefs set, right?

I have tried another terminal (in FreeBSD) in which running Vim sets `t_Co` to 8. Manually setting `t_Co` to 16 does indeed enable bright colors (such terminal is actually able to display 16 colors—why Vim's `t_Co` is set to 8 is not clear to me). Are there “real” 8-color terminals at all?

Anyway, thanks for the feedback!

**Comment by romainl** [comment]
> Is that Terminal.app? I guess you also need to have Use bright colours for bold text in the Prefs set, right?

Yes, it's Terminal.app and yes, enabling that option "fixes" that particular issue. But I feel like asking the user to perform all kinds of terminal-specific hacks just to get a Vim colorscheme working is silly.

Setting `$TERM` to `xterm-256color`/`screen-256color` should be enough to get optimal quality in basically every common terminal emulators and `xterm`/`screen` should get you a usable degraded version everywhere as well. Then, there's the `termguicolors` case which should work correctly as long as there are `cterm` values for every highlight group, which RNB does by default.

> Are there “real” 8-color terminals at all?

Maybe the Linux TTY or some similar low-level emulator?

For what it's worth… Vim's `t_Co` is set according to the `co` field of the current `$TERM` as found with:

    $ infocmp -C xterm

**Comment by lifepillar** [comment]
Thanks for the info! Your project, among others (such as disco), was a useful resource to browse for developing my Colortemplate plugin. I don’t think it interests you (obviously you don’t need it), but if you try it and spot something wrong, feedback is welcome!

**Comment by romainl** [comment]
Well yeah I don't really need it but if you want I can take a look. I'll open issues if I find funky things.

**Comment by lifepillar** [comment]
If you do check it out, please get the `v2-dev` branch (soon to be merged into master).

**Comment by romainl** [comment]
Everything is always better with some ASCII art.
