### ISSUE TITLE
Please help me understand the terminal_ansi_colors

### ISSUE THREAD

**Issue by shmup** [romainl/vim-rnb#4]
Admittedly I do not know much about the `terminal-window`

I naively generated my first pass at this with just:

```
terminal_ansi_colors = [
    black,
    lime
]
```

As my entire scheme is just black and lime. 

Then I learned to read and saw I had to satisfy all 16 indexes, so to experiment I just filled in the rest with lime. I see you warn about:

> While you are certainly free to make colors 0 to 7 shades of blue, this will inevitably cause usability issues so… be careful.

Cool, still wanna see what happens. When I test it, I see my shell theme colors coming through on say an `ls`, and maybe this is just how it works and I have to take other measures to completely make everything lime green. Even on the shell level.

Just looking for understanding, re: https://github.com/shmup/oz

**Comment by shmup** [comment]
Added a "please" just for you romainl

**Comment by romainl** [comment]
Could it be that your terminal emulator doesn't support "true colors" and/or that you didn't enable `:help 'termguicolors'`?

**Comment by shmup** [comment]
Ah hah, I did not set `termguicolors`, much thanks friend

Though I need to learn some more, as when that is enabled, vim itself is now black and white, outside of a `:terminal`  

Oops ~
